# Generated by Django 5.0 on 2026-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='tier',
            field=models.CharField(choices=[('weekly', 'Weekly (KES 100)'), ('monthly', 'Monthly (KES 400)'), ('annual', 'Annual (KES 4000)')], default='monthly', max_length=20),
        ),
    ]
