# Generated by Django 5.0 on 2025-11-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_idempotency_keys'),
        ('payments', '0002_walletdeposit'),
    ]

    operations = [
    ]
