# Generated by Django 5.0 on 2026-07-24 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_subscriptionpayment_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique uppercase promo code (e.g. BETA2026)', max_length=50, unique=True)),
                ('pro_duration_days', models.PositiveIntegerField(default=30, help_text='Number of Pro membership days granted upon redemption')),
                ('max_uses', models.PositiveIntegerField(default=100, help_text='Maximum allowed redemptions across all users')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Total number of times redeemed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether code is active and redeemable')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for promo code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_promo_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='payments.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_promo_code_redemption',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promocoderedemption',
            constraint=models.UniqueConstraint(fields=('promo_code', 'user'), name='unique_user_promo_redemption'),
        ),
    ]
