# Generated by Django 5.0 on 2025-11-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_params', models.JSONField(blank=True, null=True)),
                ('response_cached', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('flag', models.URLField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('api_id', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('referee', models.CharField(blank=True, max_length=200, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('timestamp', models.BigIntegerField()),
                ('status_long', models.CharField(max_length=100)),
                ('status_short', models.CharField(choices=[('TBD', 'Time To Be Defined'), ('NS', 'Not Started'), ('1H', 'First Half'), ('HT', 'Halftime'), ('2H', 'Second Half'), ('ET', 'Extra Time'), ('P', 'Penalty In Progress'), ('FT', 'Match Finished'), ('AET', 'Match Finished After Extra Time'), ('PEN', 'Match Finished After Penalty'), ('BT', 'Break Time'), ('SUSP', 'Match Suspended'), ('INT', 'Match Interrupted'), ('PST', 'Match Postponed'), ('CANC', 'Match Cancelled'), ('ABD', 'Match Abandoned'), ('AWD', 'Technical Loss'), ('WO', 'WalkOver')], max_length=10)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('home_goals_halftime', models.IntegerField(blank=True, null=True)),
                ('away_goals_halftime', models.IntegerField(blank=True, null=True)),
                ('home_goals_fulltime', models.IntegerField(blank=True, null=True)),
                ('away_goals_fulltime', models.IntegerField(blank=True, null=True)),
                ('home_goals_extratime', models.IntegerField(blank=True, null=True)),
                ('away_goals_extratime', models.IntegerField(blank=True, null=True)),
                ('home_goals_penalty', models.IntegerField(blank=True, null=True)),
                ('away_goals_penalty', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='fixtures.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fixtures.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fixtures.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.venue')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
