# Generated by Django 5.0 on 2025-11-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='api_key_type',
            field=models.CharField(choices=[('primary', 'Primary API Key'), ('secondary', 'Secondary API Key'), ('third', 'Third API Key')], default='primary', max_length=20),
        ),
    ]
