# Generated by Django 5.0 on 2025-11-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_add_api_key_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusagelog',
            name='api_key_type',
        ),
    ]
