# Generated by Django 5.0 on 2025-10-30 15:46

from django.db import migrations, models


def migrate_user_types(apps, schema_editor):
    """Migrate existing user_type data to new boolean fields"""
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.all():
        if profile.user_type == 'buyer':
            profile.is_buyer = True
            profile.is_tipster = False
        elif profile.user_type == 'tipster':
            profile.is_buyer = False
            profile.is_tipster = True
        else:
            # Default: set as buyer
            profile.is_buyer = True
            profile.is_tipster = False
        profile.save()


def reverse_migrate_user_types(apps, schema_editor):
    """Reverse migration - set user_type based on boolean fields"""
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.all():
        if profile.is_buyer and not profile.is_tipster:
            profile.user_type = 'buyer'
        elif profile.is_tipster and not profile.is_buyer:
            profile.user_type = 'tipster'
        else:
            # If both or neither, default to buyer
            profile.user_type = 'buyer'
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name='userprofile',
            name='is_buyer',
            field=models.BooleanField(default=True, help_text='Can purchase tips from tipsters'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_tipster',
            field=models.BooleanField(default=False, help_text='Can share tips and earn revenue'),
        ),
        # Migrate existing data
        migrations.RunPython(migrate_user_types, reverse_migrate_user_types),
        # Remove old field
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
