# Generated by Django 5.0 on 2026-07-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('textract', 'AWS Textract'), ('easyocr', 'EasyOCR'), ('sportpesa', 'SportPesa Scraper'), ('gemini', 'Gemini AI (Fast & Accurate)'), ('gemini_langextract', 'Gemini + LangExtract (Best Quality)')], default='gemini_langextract', help_text='Select which OCR provider to use for processing betslips. Gemini + LangExtract is recommended for best performance and accuracy.', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OCR Provider Setting',
                'verbose_name_plural': 'OCR Provider Settings',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_code', models.CharField(max_length=50, unique=True)),
                ('bookmaker', models.CharField(choices=[('betika', 'Betika'), ('sportpesa', 'SportPesa'), ('betin', 'Betin'), ('mozzart', 'Mozzart'), ('odibets', 'Odibets'), ('other', 'Other')], default='betika', max_length=20)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='betslips/')),
                ('bet_sharing_link', models.URLField(blank=True, help_text='SportPesa bet sharing/referral link', max_length=500, null=True)),
                ('match_details', models.JSONField(default=dict, help_text='OCR extracted match details')),
                ('preview_data', models.JSONField(default=dict, help_text='Preview data for buyers')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('active', 'Active'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='pending_approval', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When tip expires (last match start time)')),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], default='completed', help_text='Status of background processing', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('enrichment_completed', models.BooleanField(default=False, help_text='Whether API-Football enrichment is complete')),
                ('is_resulted', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('result_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, max_length=100)),
                ('match_date', models.DateTimeField()),
                ('market', models.CharField(max_length=100)),
                ('selection', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_resulted', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('actual_result', models.CharField(blank=True, max_length=100)),
                ('api_match_id', models.CharField(blank=True, help_text='API-Football match ID', max_length=50)),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
    ]
