# Generated by Django 5.0 on 2026-07-12 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrprovidersettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='tipster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipmatch',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tips.tip'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['status', 'created_at'], name='tips_tip_status_9b0e25_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['tipster', 'status'], name='tips_tip_tipster_221a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['expires_at'], name='tips_tip_expires_1c24b9_idx'),
        ),
    ]
