# Generated by Django 5.0 on 2025-11-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_ocrprovidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='bet_sharing_link',
            field=models.URLField(blank=True, help_text='SportPesa bet sharing/referral link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ocrprovidersettings',
            name='provider',
            field=models.CharField(choices=[('textract', 'AWS Textract'), ('easyocr', 'EasyOCR'), ('sportpesa', 'SportPesa Scraper')], default='textract', help_text='Select which OCR provider to use for processing betslips', max_length=20),
        ),
        migrations.AlterField(
            model_name='tip',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='betslips/'),
        ),
    ]
