# Generated by Django 5.0 on 2026-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='preview_data',
            field=models.JSONField(default=dict, help_text='Preview data for non-Pro users'),
        ),
    ]
