# Generated by Django 5.0 on 2025-11-08 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_add_sportpesa_scraper_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='Start of payment period')),
                ('period_end', models.DateTimeField(help_text='End of payment period')),
                ('total_revenue', models.DecimalField(decimal_places=2, help_text='Total revenue from tip sales in this period', max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=40.0, help_text='Platform commission percentage (default: 40%)', max_digits=10)),
                ('tipster_share', models.DecimalField(decimal_places=2, help_text='Amount to be paid to tipster (60% of revenue)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='M-Pesa confirmation code or bank reference', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='M-Pesa phone number', max_length=15)),
                ('tips_count', models.IntegerField(default=0, help_text='Number of tips sold in this period')),
                ('purchases_count', models.IntegerField(default=0, help_text='Number of purchases in this period')),
                ('notes', models.TextField(blank=True, help_text='Payment notes or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
                ('tipster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipster Payment',
                'verbose_name_plural': 'Tipster Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipster', 'status'], name='tips_tipste_tipster_2f384b_idx'), models.Index(fields=['period_start', 'period_end'], name='tips_tipste_period__5eb838_idx'), models.Index(fields=['status', 'created_at'], name='tips_tipste_status_745e7f_idx')],
            },
        ),
    ]
