# Generated by Django 5.0 on 2025-11-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_tipsterpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='enrichment_completed',
            field=models.BooleanField(default=False, help_text='Whether API-Football enrichment is complete'),
        ),
        migrations.AddField(
            model_name='tip',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], default='completed', help_text='Status of background processing', max_length=20),
        ),
    ]
