# Generated by Django 5.0 on 2025-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_add_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrprovidersettings',
            name='provider',
            field=models.CharField(choices=[('textract', 'AWS Textract'), ('easyocr', 'EasyOCR'), ('sportpesa', 'SportPesa Scraper'), ('gemini', 'Gemini AI (Fast & Accurate)')], default='gemini', help_text='Select which OCR provider to use for processing betslips. Gemini AI is recommended for best performance.', max_length=20),
        ),
    ]
