# Generated by Django 5.0 on 2025-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_add_gemini_ocr_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrprovidersettings',
            name='provider',
            field=models.CharField(choices=[('textract', 'AWS Textract'), ('easyocr', 'EasyOCR'), ('sportpesa', 'SportPesa Scraper'), ('gemini', 'Gemini AI (Fast & Accurate)'), ('gemini_langextract', 'Gemini + LangExtract (Best Quality)')], default='gemini_langextract', help_text='Select which OCR provider to use for processing betslips. Gemini + LangExtract is recommended for best performance and accuracy.', max_length=25),
        ),
    ]
